### ISSUE TITLE
Testing support on AWS

### ISSUE THREAD

**Issue by benedictpaten** [ga4gh/server#335]
We would like to put up a reference server on AWS for testing, and ultimately, wider, general use. 

The dataset we should use for testing is probably:

http://aws.amazon.com/1000genomes/

It would be good to test read and variant support.

Assuming @dcolligan takes this on at UCSC, Hannes or Mark can give you our AWS account details.

**Comment by dcolligan** [comment]
I have a server set up with example data at this address now:

http://ec2-54-200-59-190.us-west-2.compute.amazonaws.com/ga4gh/

But I'm stopping the instance until I figure out the configuration with the 1000 genomes data set.

**Comment by dcolligan** [comment]
#339 and #340 need to be fixed before we can test remote reads and variants

Also, @benedictpaten , can you be more specific about the list of files you would like to see served?  There is a lot of stuff in that s3 bucket.

**Comment by benedictpaten** [comment]
Hmm, as a starting point I don't think it matters which bam/vcf files we
use. I tried looking through the s3 bucket but I'm totally confused about
what's there. Is there a sensible way of viewing/navigating it. Sorry for
the stupid question.

**Comment by dcolligan** [comment]
Yeah, are there any external docs that describe the contents of this project?

There are some READMEs scattered around that bucket.  What's annoying is that the standard command for interacting with s3, `s3cmd`, requires credentials to set up (AFAICT) meaning that a non-credentialed user just can't use it for public buckets.  I've written a tool to download them: https://github.com/dcolligan/server/blob/335_aws_deploy/scripts/save_1000g_readmes.py

**Comment by benedictpaten** [comment]
Okay, I'll take a look at the read-mes shortly. Thanks!

**Comment by delagoya** [comment]
Graphical clients that support S3 should be able to see the directory with ab anonymous login: 

![s3_amazonaws_com_ _s3_and_testing_support_on_aws_ _issue__335_ _ga4gh_server](https://cloud.githubusercontent.com/assets/710/7210485/28705152-e520-11e4-88d4-f515bd2ebe22.png)

Also the s3 bucket is a complete mirror of the FTP site, so you can get a listing of files from that.

**Comment by delagoya** [comment]
Also note that Genome in a Bottle is also on S3 at http://giab.s3.amazonaws.com

**Comment by dcolligan** [comment]
@delagoya what client is that that you're using?

**Comment by delagoya** [comment]
The excellent and open source Cyberduck 

https://cyberduck.io/?l=en

**Comment by jeromekelleher** [comment]
Marking this as blocked until we have access to the libcurl based htslib code. 

See #612 for discussion.

**Comment by diekhans** [comment]
Andreas has support for  htslib 1.3 in pysam and would like feedback before releasing.
Danny or Maciek, can you verify this???

https://github.com/pysam-developers/pysam/issues/195#issuecomment-174350988

**Comment by dcolligan** [comment]
Looks like @jeromekelleher is on it.

**Comment by AndreasHeger** [comment]
Thanks all. About libcurl, I have taken it out of the htslib that comes with pysam. I was worried that it would cause widespread compilation issues. For example, on our redhat system, libcurl was present but too old. To use libcurl, please make sure you link pysam against an external htslib with libcurl support.

To do this, please set the HTSLIB_LIBRARY_DIR and HTSLIB_INCLUDE_DIR environment variables when running python setup.py install 

Best, Andreas

**Comment by jeromekelleher** [comment]
Thanks for clarifying this @AndreasHeger. When you say libcurl is taken out, does that mean we fall back on the old networking code, or is there no support for remote files? Does the bdist_wheel that you built for pysam 0.8.5 use libcurl?

**Comment by AndreasHegerGenomics** [comment]
Hi @jeromekelleher, there is support for remote files, but without libcurl. The htslib coming with pysam is compiled without running configure and thus defaults to "conservative setttings" according to the docs. I think that the pysam-0.8.5 wheel also does not include libcurl. I can create a wheel that will use a system-installed htslib and upload it this evening.

**Comment by jeromekelleher** [comment]
Ah OK, thanks. Would it be possible to put a function in pysam to report on whether libcurl is in use or not? This would make it easier to test whether our compilation has succeeded.

**Comment by AndreasHegerGenomics** [comment]
certainly, will think of something.

**Comment by jeromekelleher** [comment]
Great, thanks @AndreasHegerGenomics.

**Comment by AndreasHeger** [comment]
@jeromekelleher, I have looked into this, but I am not sure on how to get functionality of an external htslib at runtime. I can return the configuration of included htslib at compiletime, but that will probably be of limited help. I am still following this up, though.

Anyways, I have updated the wheel to link against an external htslib.

**Comment by pgrosu** [comment]
Hi Andreas,

Do you mean something like dynamic importing of modules, such as something like this:

1) If I have a file called `external_function.py` with the following contents:

```Python
def mysum(x, y):
	return int(x) + int(y)
```
2) And in my main file that I run - which I call `my_external_test.py` - I have the following:

```Python
import sys 

def main():
 
 	extsum = __import__(sys.argv[3]);

	x = sys.argv[1]
	y = sys.argv[2]

	print( extsum.mysum(x,y) );

# Insures that the starting function is the main function

if __name__ == "__main__":
    main()
```

So the results of what I run would be the following:

```Bash
> python my_external_test.py 3 4 external_function
7
```

Let me know if this is what you were looking for.

Thanks,
Paul

**Comment by jeromekelleher** [comment]
Compile-time configuration would still be a big help @AndreasHegerGenomics, as we would very much prefer to install entirely from pip rather than link against an external htslib. Would it be possible to make compiling htslib with libcurl support an option? I'm happy to do some work on this if it would help.

**Comment by jmarshall** [comment]
You can tell whether an underlying htslib is using libcurl or the old _knetfile.c_ code by trying to open an `https://…` or `HTTP://…` URL.  Only libcurl can do `https`, and only libcurl understands uppercase URL schemes.

@AndreasHeger: What version of Red Hat are you on, and what version of libcurl does it come with?  (And have you considered upgrading to something less prehistoric? :smile:)

**Comment by pgrosu** [comment]
Hi John/Andreas,

Would it not it just be easier to perform that via `objdump` by going into the `pysam` python package install directory, and performing the following:

```Bash
[pysam]$ objdump -x libchtslib.so  | grep knet
0000000000000000 l    df *ABS*  0000000000000000              knetfile.c
00000000000264f0 g     F .text  000000000000012b              knet_open
0000000000026120 g     F .text  000000000000001d              knet_dopen
0000000000026350 g     F .text  0000000000000125              knet_seek
0000000000026140 g     F .text  000000000000020e              knet_read
0000000000026480 g     F .text  0000000000000065              knet_close
[pysam]$ objdump -x libchtslib.so  | grep curl
```

Paul

**Comment by jmarshall** [comment]
@pgrosu That won't work if htslib has been configured with the libcurl backend as a separate plugin (not that that will happen as long as pysam isn't running htslib's configure).  Whether it sees and uses a libcurl plugin is a runtime decision, so best to do some kind of runtime test.  Ideally htslib would have some way of enumerating plugins and/or URL schemes understood, which is samtools/samtools#367 and following.

(Note that the knet functions will always be present in libchtslib.so as a fallback.)

**Comment by jeromekelleher** [comment]
What would be the steps we need to take the enable the libcurl plugin without running ``./configure --enable-libcurl`` @jmarshal? It would be a _lot_ easier for our users if we can install pysam directly with pip rather than requiring them to compile and install htslib, install it into a non-standard location, manage LD_LIBRARY_PATH and all that messiness.

Ideally, we would like to set an environment variable (e.g.) PYSAM_USE_LIBCURL that pysam's setup.py can detect and alter the build process accordingly. What do you think @AndreasHegerGenomics, would this be a reasonable approach? I.e., we fall back on the current safe approach if the variable isn't set, and if it is, it's up to the user to ensure that libcurl can be found by the compiler by setting CFLAGS, LDFLAGS etc.

**Comment by AndreasHeger** [comment]
Thanks, that is all very helpful. I propose to do the following:

1. run configure with increasingly conservative settings. configure is quite fast, so should not be too much of an issue, looking for an env variables as well, such as HTSLIB_CONFIGURE_OTPTIONS
2. If configure fails, revert to the default, conservative config.h
3. create a version.py from a template that echo's the htslib mode (external/built-in) and exports the settings in config.h in the latter case.

@jmarshall, the system is a RH6 system with libcurl 7.19.7-37.el6_4. It fails at
```
hfile_libcurl.c: In function 'easy_errno':
hfile_libcurl.c:93: error: 'CURLE_NOT_BUILT_IN' undeclared (first use in this function)
hfile_libcurl.c:93: error: (Each undeclared identifier is reported only once
hfile_libcurl.c:93: error: for each function it appears in.)
```

CURLE_NOT_BUILT_IN only came in 7.21.5, see
http://curl.haxx.se/libcurl/c/symbols-in-versions.html

Best wishes,
Andreas

**Comment by pgrosu** [comment]
Many thanks Andreas helping us out.  Your instructions are very simple and straightforward.

Hi Jerome, et al.,

I did something similar based on some of the recommendations by Andreas and the group, and I just tested the following process, which worked like a charm - *notice the `libcurl` at the end*:

```Bash
$ wget --quiet https://pypi.python.org/packages/source/p/pysam/pysam-0.8.4.tar.gz
$ tar zxvf pysam-0.8.4.tar.gz
$ cd pysam-0.8.4
$ wget --quiet https://github.com/samtools/htslib/releases/download/1.3/htslib-1.3.tar.bz2
$ tar xjvf htslib-1.3.tar.bz2
$ cd htslib-1.3
$ ./configure --enable-libcurl
$ make
$ cd ..
$ export HTSLIB_LIBRARY_DIR=`pwd`/htslib-1.3
$ export HTSLIB_INCLUDE_DIR=`pwd`/htslib-1.3
$ export MY_PYTHON_PKGS=`python -c "import site; print(site.USER_SITE)"`
$ python setup.py install --user
$ export CURRENT_DIR=`pwd`
$ cd $MY_PYTHON_PKGS
$ cd `ls -t | grep pysam | head -n1`/pysam
$ cp $CURRENT_DIR/htslib-1.3/libhts.so .
$ ln -s libhts.so libhts.so.1
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
$ ldd libchtslib.so | grep curl
        libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00002aaaabd8d000)
$ cd $CURRENT_DIR
```

You can put it all in script if you want, and it will work like magic :smile:

Have a great weekend everyone!
~p

**Comment by AndreasHeger** [comment]
Thanks for testing. I have put a new version of the tar-ball that will run configure here:

https://www.cgat.org/downloads/public/pysam/sdist/psyam-0.8.5.tar.gz

To pass options to the configure script, set HTSLIB_COMPILE_OPTIONS

Best wishes,
Andreas

**Comment by pgrosu** [comment]
Hi Andreas,

Thank you for providing the updated version.  Here are a few things:

1) The `psyam-0.8.5.tar.gz` probably should be renamed as `pysam-0.8.5.tar.gz` :)

2) Regarding defining `PLUGINPATH` for `htslib`, would that also be defined through `HTSLIB_COMPILE_OPTIONS` or somewhere else?  I tried the following and it didn't work:

```Bash
./configure --enable-plugins PLUGINPATH=\"/home/pgrosu/test/htslib\"
```

When the `make` is performed, one still sees something like this, with `PLUGINPATH` being assigned `/usr/local/libexec/htslib`:

```
gcc -g -O2 -I. -DPLUGINPATH=\"/usr/local/libexec/htslib\" -c -o plugin.o plugin.c
```

3) And now for the test of truth :) So for this test I did the following to make it work, as I sometimes got some errors:

* Configured `HTSLIB_MODE="external"`,
* Configured `HTSLIB_COMPILE_OPTIONS="--enable-libcurl"`,
* Downloaded the `htslib-1.3` from the web,
* Renamed the original `htslib` directory as `htslib-orig`,
* Created a `htslib` symbolic link to point to the new downloaded and extracted `htslib-1.3` folder,
* Just to be sure the `htslib.so` got generated, I ran `./configure --enable-libcurl`, and then ran `make` from the `htslib` directory - both of which I ran manually.

So without further ado, below are all the steps that I performed:

```Bash
$ wget --quiet https://www.cgat.org/downloads/public/pysam/sdist/psyam-0.8.5.tar.gz
$ tar zxvf psyam-0.8.5.tar.gz
$ cd psyam-0.8.5
$ wget --quiet https://github.com/samtools/htslib/releases/download/1.3/htslib-1.3.tar.bz2
$ tar xjvf htslib-1.3.tar.bz2
$ mv htslib htslib-orig
$ ln -s htslib-1.3 htslib
$ export HTSLIB_COMPILE_OPTIONS="--enable-libcurl"
$ export HTSLIB_MODE="external"
$ export HTSLIB_LIBRARY_DIR=`pwd`/htslib
$ export HTSLIB_INCLUDE_DIR=`pwd`/htslib
$ cd htslib
$ ./configure --enable-libcurl
$ make
$ cd ..
$ cp setup-with-make.py setup.py
$ python setup.py install --user
$ export MY_PYTHON_PKGS=`python -c "import site; print(site.USER_SITE)"`
$ export CURRENT_DIR=`pwd`
$ cd $MY_PYTHON_PKGS
$ cd `ls -t | grep psyam | head -n1`/pysam
$ cp $CURRENT_DIR/htslib-1.3/libhts.so .
$ ln -s libhts.so libhts.so.1
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
$ ldd libchtslib.so | grep curl
        libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00002aaaabd8d000)
$ cd $CURRENT_DIR
```

Thank you,
Paul

**Comment by jeromekelleher** [comment]
Thanks for this @AndreasHeger, this sounds like a great approach. I've tried it out, but I think the configure script isn't being included in the tarball. Should it be added to MANIFEST.in?

**Comment by AndreasHeger** [comment]
Thanks all. 

@jeromekelleher,  updated and (briefly) tested.

@pgrosu,
Re 1: Saturday night I was staring at it for minutes and did not see the psyam/pysam diffference. Thanks!

Re 2: The following should work: 
```
export HTSLIB_COMPILE_OPTIONS="--enable-plugins --with-plugin-path=/usr/local/lib"
python setup.py install
```
but not tested.

Re 3: To link against an external htslib, no editing/changing of the htslib dir should be needed:
```
export HTSLIB_LIBRARY_DIR=/usr/local/lib
export HTSLIB_INCLUDE_DIR=/usr/local/include
python setup.py install
```

This will ignore the htslib code that comes within the pysam tarball/repository.

I will add installation instructions to the docs and also add them to the travis. Currently, only install from the repository is tested, but not from the tarball.

**Comment by jmarshall** [comment]
> RH6 system with libcurl 7.19.7-37.el6_4. It fails at
> hfile_libcurl.c:93: error: 'CURLE_NOT_BUILT_IN' undeclared (first use in this function)

Thanks, fixed in samtools/htslib@2805ae8041f2d49b889d0b4f54c53070e4791dbb.  It would be appreciated if you would [report these problems upstream](https://github.com/samtools/htslib), as then there is an opportunity to get them fixed!

Miscellaneous comments:

* Please make that environment variable `HTSLIB_CONFIGURE_OPTIONS` as you originally proposed: these are configure options, not compile options.
* The plugin path configure options are described in [htslib/INSTALL](https://github.com/samtools/htslib/blob/1.3/INSTALL#L45-L53).  HTSlib considers all the files that match certain patterns in these directories, so it's recommended to make them a bespoke subdirectory.  So `--with-plugin-path=/usr/local/libexec/htslib`, which is in fact the default.

    See [samtools/README](https://github.com/samtools/samtools/blob/1.3/README#L6-L7) for plugin path suggestions for running-in-place rather than installing HTSlib.

**Comment by jeromekelleher** [comment]
I've just got around to trying this out @AndreasHeger (sorry for the delay), and I'm hitting an obscure run-time error:
```
  File "/home/jk/.local/lib/python2.7/site-packages/pysam/__init__.py", line 3, in <module>
    from pysam.cutils import *
ImportError: /home/jk/.local/lib/python2.7/site-packages/pysam/cutils.so: undefined symbol: reset_getopt
```
I just ran pip install <tarball>, and didn't set any env variables.

**Comment by jmarshall** [comment]
@jeromekelleher Seems like you're in need of some `make clean` or equivalent: `reset_getopt` disappeared at the weekend in pysam-developers/pysam@7954ff1a6df7a4a7e088e7b17bfd4e9868bb94dc.

**Comment by pgrosu** [comment]
@AndreasHeger, @jmarshall, @jeromekelleher - We might be close, but I had to go through many failures of errors over the weekend until I came up with the procedures I put above.  Ideally what I would like to see is a similar step-by-step that will always work without any issues, which is what I did before posting the procedures.  Hopefully all edge-cases will be tackled, and this way users would not need to think about the process, and would just follow it with the expectation that everything will work.

`p

**Comment by jeromekelleher** [comment]
Thanks for the pointers @jmarshall --- I'm building directly from the pysam repo now, and it's working well. I'm still not able to open https URLS, but I'm sure it's getting close. Just so I understand what's going on here, there _must_ be a separate .so file (or whatever) in some directory for the libcurl plugin, which htslib searches at run time? I.e., there's no option to compile in libcurl directly into the main library?

**Comment by AndreasHeger** [comment]
@jeromekelleher , quick thought, will check later tonight. It might be that for builtin htslib I will need to add libcurl as a link dependency. The current setup might compile in libcurl ability, but then the library is not pulled in at runtime. Do you have a https:// BAM that I could use for testing?

**Comment by pgrosu** [comment]
@jeromekelleher In the `setup.py` file you will see the following:

```Python
cutils = Extension(
    "pysam.cutils",
    [source_pattern % "utils", "pysam/pysam_util.c"] +
    glob.glob(os.path.join("samtools", "*.pysam.c")) +
    # glob.glob(os.path.join("samtools", "*", "*.pysam.c")) +
    glob.glob(os.path.join("bcftools", "*.pysam.c")) +
    # glob.glob(os.path.join("bcftools", "*", "*.pysam.c")) +
    htslib_sources +
    os_c_files,
    library_dirs=["pysam"] + htslib_library_dirs,
    include_dirs=["samtools", "bcftools", "pysam"] +
    include_os + htslib_include_dirs,
    libraries=["z"] + htslib_libraries,
    language="c",
    extra_compile_args=extra_compile_args,
    define_macros=define_macros
)
```

The following two links will help with what is happening:

https://docs.python.org/2/extending/building.html

https://docs.python.org/3/extending/building.html

On my system, after the above build I see the expected following files:

```Bash
$ find . | grep cutils
./pysam/cutils.pxd
./pysam/cutils.c
./pysam/cutils.pyx
./build/lib.linux-x86_64-2.7/pysam/cutils.pxd
./build/lib.linux-x86_64-2.7/pysam/cutils.so
./build/temp.linux-x86_64-2.7/pysam/cutils.o
$
```

Looking at the `setup.py` file might help clarify why some things are happening.

Hope it helps,
~p

**Comment by jeromekelleher** [comment]
Thanks for looking into it @AndreasHeger.

>  Do you have a https:// BAM that I could use for testing?

Unfortunately not, the server I'm using is behind the firewall...

**Comment by jeromekelleher** [comment]
Hmmm, reading the configure help we have
> --enable-plugins
    Use plugins to implement exotic file access protocols and other
    specialised facilities.  This enables such facilities to be developed
    and packaged outwith HTSlib, and somewhat isolates HTSlib-using programs
    from their library dependencies.  By default, any enabled pluggable
    facilities (such as iRODS and libcurl file access) are built directly
    within HTSlib.

So, it does sound like we should be able to build the plugins directly into htslib.

**Comment by jmarshall** [comment]
If you configure with `--enable-libcurl` but without `--enable-plugins` then the `libhts.{a,so}` produced will have libcurl capabilities burnt into it and will not search for hfile plugins at runtime.  If pysam links against `libhts.so.1` all will be well (but that _libhts.so.1_ will also need to be available when you run pysam-using code).  OTOH if pysam links against `libhts.a` it will have to take extra steps to link against `-lcurl -lcrypto` or so as well — compare `LIBCURL_LIBS` in _htslib/config.mk.in_.

**Comment by jeromekelleher** [comment]
Great, thanks @jmarshall; I'm poking through it now, think I see the problem...

**Comment by pgrosu** [comment]
@jeromekelleher That is always the fail-safe way :smile:

**Comment by jeromekelleher** [comment]
Some progress made in https://github.com/pysam-developers/pysam/pull/217, but not quite there yet.

**Comment by AndreasHeger** [comment]
@jmarshall , thanks I will report more. I did agree that it was an issue of an old, unsupported system.

> Please make that environment variable HTSLIB_CONFIGURE_OPTIONS as you originally proposed: these are configure options, not compile options.
DONE

    The plugin path configure options are described in htslib/INSTALL. HTSlib considers all the files that match certain patterns in these directories, so it's recommended to make them a bespoke subdirectory. So --with-plugin-path=/usr/local/libexec/htslib, which is in fact the default.

    See samtools/README for plugin path suggestions for running-in-place rather than installing HTSlib.
Thanks!

**Comment by AndreasHeger** [comment]
@pgrosu and @jeromekelleher  I have added installation instructions here:

http://pysam.readthedocs.org/en/latest/installation.html

Admittedly, they might describe an ideal state not yet achieved.

**Comment by jeromekelleher** [comment]
I've been digging through this a bit more @AndreasHeger, and it looks like libcurl is being used for HTTP transactions, but HTTPS opens are failing sometime before ``hFILE.hopen``:
```
(test-env)jk@holly$ python dev.py
Finding handler for 'http://holly.well.ox.ac.uk/~jk/HG00096.bam'
Got: 'libcurl'
Finding handler for 'http://holly.well.ox.ac.uk/~jk/HG00096.bam.csi'
Got: 'libcurl'
Finding handler for 'http://holly.well.ox.ac.uk/~jk/HG00096.csi'
Got: 'libcurl'
Finding handler for 'HG00096.bam.bai'
dbb6e8ece0b5de29da56601613007c2a
Traceback (most recent call last):
  File "dev.py", line 7, in <module>
    af = pysam.AlignmentFile("https://holly.well.ox.ac.uk/~jk/HG00096.bam")
  File "pysam/calignmentfile.pyx", line 326, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4564)
  File "pysam/calignmentfile.pyx", line 398, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:5485)
  File "pysam/calignmentfile.pyx", line 546, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:6983)
IOError: file `https://holly.well.ox.ac.uk/~jk/HG00096.bam` not found
```
I bunged some printfs into hfile.c to see what was going on with the handlers. I think we're quite close to sorting this out now.

**Comment by AndreasHeger** [comment]
Thanks, @jeromekelleher and many thanks for perservering. I currently don't have a way to test this, otherwise I would help. On MondayI will talk to our sysadmin if there is a server I can use to test.

Will command-line samtools connect to the file without problems?

**Comment by delagoya** [comment]
I can volunteer AWS resources for this effort. Please email me directly at angel at amazon com

**Comment by pgrosu** [comment]
Thanks Angel (@delagoya) for helping us out with resources - it is very appreciated!

@AndreasHeger, I looked at the installation instructions and they looks very nice - and understandably is an ideal state to achieve, which I also strive for.  Just a couple of things:

When it says:

> If these fail, for example due to missing library dependencies (libcurl, libcrypto), it will fall back to conservative defaults.

I feel that the program should automatically try to get the required dependencies off the web, adapt itself to the installation environment and provide the user what he/she requested, without negatively affecting the installation environment.  For instance, @ekg's [vg](https://github.com/ekg/vg) will gather all the necessary dependencies to build itself.  The installation program should be a finite state machine that tries all possibilities to deliver to the user what he/she requested.

For instance, if I performed the following it still falls on the defaults as noted:

```Bash
$ export HTSLIB_CONFIGURE_OPTIONS="--enable-plugins --enable-libcurl"
$ pip install pysam
$ ldd ./lib/python2.7/site-packages/pysam/libchtslib.so | grep curl
$ objdump -x ./lib/python2.7/site-packages/pysam/libchtslib.so | grep knet
0000000000000000 l    df *ABS*  0000000000000000              knetfile.c
0000000000021670 g     F .text  000000000000012b              knet_open
00000000000212b0 g     F .text  000000000000001d              knet_dopen
00000000000214d0 g     F .text  0000000000000125              knet_seek
00000000000212d0 g     F .text  00000000000001fe              knet_read
0000000000021600 g     F .text  0000000000000065              knet_close
$
```

I know @jeromekelleher is helping us out with integration of `libcurl`, which is awesome!  And hopefully the installation script is able to learn from the installation environment, and adapt accordingly to install what the user wants in the way he/she wants to.  For instance, it should be a one-line thing and straight-forward:

```Bash
$ get-for-python.sh pysam --with-builtin="libcurl, plugins" --in-user-home
```
This way the `get-for-python.sh` script does what it needs to provide to the user the requested features.  We have to always adapt to the our users, and make the GA4GH reference server a turn-key solution, where the majority of folks will think it just works without any major intervention.  This will make adopting new users to GA4GH much easier.  Again, I fully appreciate all the hard work by everyone, but I strongly feel about having the machine adapt to the user, and not the other way around.  It is something I strive in all my programs, and am always pleasantly surprised by the end-user reaction.

Hope folks feel comfortable with this approach.

Paul

**Comment by jeromekelleher** [comment]
After playing with a bit more, I realise that I wasn't actually compiling the Cython code, and so the update to get 'https' recognised as a remote URL wasn't working. After fixing this, we now pass the URL down to htslib and the libcurl handler is invoked correctly. However, we're still not successfully opening the https URLs:
```
Finding handler for 'https://holly.well.ox.ac.uk/~jk/HG00096.bam'
Got: 'libcurl'
[E::hts_open_format] fail to open file 'https://holly.well.ox.ac.uk/~jk/HG00096.bam'
Traceback (most recent call last):
  File "dev.py", line 7, in <module>
    af = pysam.AlignmentFile("https://holly.well.ox.ac.uk/~jk/HG00096.bam")
  File "pysam/calignmentfile.pyx", line 326, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4803)
  File "pysam/calignmentfile.pyx", line 414, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:5956)
  File "pysam/calignmentfile.pyx", line 561, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7604)
ValueError: could not open file (mode='r') - is it SAM/BAM format?
```
Apache doesn't report any attempts at reading the file in its logs.

Anyway, I don't think we need https support right now, just getting libcurl access to plain ole http should get us up and running on Amazon and other cloud stores. @delagoya, some help from AWS on getting https, s3 etc protocol support in pysam would be great!

**Comment by jmarshall** [comment]
> Finding handler for 'https://holly.well.ox.ac.uk/~jk/HG00096.bam'
> Got: 'libcurl'
> [E::hts_open_format] fail to open file 'https://holly.well.ox.ac.uk/~jk/HG00096.bam'

Set `hts_verbose` to 8 or more, and libcurl will give you lots of information about what went wrong between these two lines.  (I can't remember whether pysam acquired a function for setting `hts_verbose` or not…)

**Comment by jeromekelleher** [comment]
Aha, good call, thanks @jmarshall 
```
Finding handler for 'https://holly.well.ox.ac.uk/~jk/HG00096.bam'
Got: 'libcurl'
* Hostname was found in DNS cache
*   Trying 127.0.1.1...
* Connected to holly.well.ox.ac.uk (127.0.1.1) port 443 (#1)
* found 174 certificates in /etc/ssl/certs/ca-certificates.crt
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 1
[E::hts_open_format] fail to open file 'https://holly.well.ox.ac.uk/~jk/HG00096.bam'
```
Obviously we don't want to accept self-signed certs by default, but this should be configurable (curl for example is happy to read from the server, but wget refuses). What's the recommended approach for interacting with libcurl here? 

On a side note, It doesn't look like ``pysam.set_verbosity()`` works when building pysam in 'separate' mode (I updated the C code to get the trace above). It seems likely that this is because we have several different copies of htslib compiled, and we would need to set ``hts_verbose`` separately for each one. This will be essential for debugging these sorts of issues.

**Comment by AndreasHeger** [comment]
@pgrosu , many thanks for your comments. I agree that installation should be as painless as possible. 

With respect to the pysam code base, however, I think the best place to solve installation issues is on a level above pysam, whether it is through a wrapper script (as you suggested), rpm dependencies, conda, docker, etc.

I am worried that if pysam tries to be too ambitious, i.e., trying to download dependencies (outside of pypi) that need to be configured and installed properly, we will spend a lot of effort troubleshooting user installation issues that are not necessarily related to the code we support. The principal reason for including htslib/samtools, etc. within the pysam tarball is to enable novice users to be able to access htslib awesomeness without having to install system libraries, set library paths, etc. As a consequence, the install is a bit biased towards conservative choices.

For advanced users and those building environments, I hope that as long as setup.py can be configured easily so that it can work nicely together with different packaging methods, that this should be sufficient for advanced users. Happy to include anything that makes this process easier into setup.py.

Hope this makes sense, comments appreciated.

**Comment by AndreasHeger** [comment]
https://github.com/pysam-developers/pysam/issues/223@jeromekelleher, thanks interesting. I have opened an issue on pysam, see

**Comment by pgrosu** [comment]
Hi Andreas (@AndreasHeger),

So almost anything is possible, and sorry to reply so late as I got swamped with other things these week.  I was able to perform some updates to `setup.py`, which will allow for the `htslib` library to be built-in - something I think that Jerome (@jeromekelleher) might also enjoy :)   So the updates to `setup.py` perform the following tasks:

* Downloads `htslib-1.3.tar.bz2`, and compile it as a static library,
* Compiles `pysam` with full integration of `libhts.a` into `libchtslib.so`, which eliminates both the `LD_LIBRARY_PATH` configuration and `libhts.so` shared library requirements.

Below are all the steps that enable the above functionality.  You will notice near the end that `libcurl` functionality is available, but no requirement for the shared library `libhts.so` is necessary:

```Bash
$ wget --quiet https://www.cgat.org/downloads/public/pysam/sdist/pysam-0.8.5.tar.gz
$
$ tar zxvf pysam-0.8.5.tar.gz
$ cd pysam-0.8.5
$
$ export HTSLIB_COMPILE_OPTIONS="--enable-libcurl" 
$ export HTSLIB_LIBRARY_DIR=`pwd`/htslib
$ export HTSLIB_INCLUDE_DIR=`pwd`/htslib
$
$ sed "412s/ + htslib_libraries//" setup.py > setup.py-fix-1
$ rm setup.py
$ mv setup.py-fix-1 setup.py
$
$ sed -i "34iimport urllib" setup.py
$ sed -i "110ihtsfile = urllib.URLopener()" setup.py
$ sed -i "111ihtsfile.retrieve(\"http://iweb.dl.sourceforge.net/project/samtools/samtools/1.3/htslib-1.3.tar.bz2\", \"htslib-1.3.tar.bz2\")" setup.py
$ sed -i "112ios.system(\"tar xjvf htslib-1.3.tar.bz2\")" setup.py
$ sed -i "113ios.system(\"mv htslib htslib-orig\")" setup.py
$ sed -i "114ios.system(\"ln -s htslib-1.3 htslib\")" setup.py
$ sed -i "115isavedPath = os.getcwd()" setup.py
$ sed -i "116ios.chdir(\"htslib\")" setup.py
$ sed -i "117ios.system(\"./configure --enable-libcurl\")" setup.py
$ sed -i "118ios.system(\"make lib-static CFLAGS=-fPIC\")" setup.py
$ sed -i "119ios.chdir(savedPath)" setup.py
$ sed -i "120i\ " setup.py
$ 
$ sed -i "414iextra_link_args = []" setup.py
$ sed -i "415iextra_link_args.append(\"-Wl,--whole-archive\")" setup.py
$ sed -i "416iextra_link_args.append(\"htslib/libhts.a\")" setup.py
$ sed -i "417iextra_link_args.append(\"-Wl,--no-whole-archive\")" setup.py
$ 
$ sed -i "431i\ \ \ \ extra_link_args=extra_link_args," setup.py
$ 
$ python setup.py install --user
$ 
$ export MY_PYTHON_PKGS=`python -c "import site; print(site.USER_SITE)"`
$ export CURRENT_DIR=`pwd`
$ cd $MY_PYTHON_PKGS
$ cd `ls -t | grep pysam | head -n1`/pysam
$ ldd libchtslib.so 
        linux-vdso.so.1 =>  (0x00007ffff7ffe000)
        libz.so.1 => /lib64/libz.so.1 (0x00007ffff7b1f000)
        libpython2.7.so.1.0 => /cm/shared/engaging/python/2.7.9/lib/libpython2.7.so.1.0 (0x00007ffff773d000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffff7520000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff718c000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff6f87000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007ffff6d84000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffff6b00000)
        /lib64/ld-linux-x86-64.so.2 (0x00000039a2a00000)
$ objdump -x libchtslib.so | grep libcurl
0000000000000000 l    df *ABS*  0000000000000000              hfile_libcurl.c
0000000000098bd6 l     F .text  0000000000000058              libcurl_exit
0000000000098fdb l     F .text  0000000000000150              libcurl_read
00000000000991f9 l     F .text  0000000000000150              libcurl_write
0000000000099349 l     F .text  0000000000000346              libcurl_seek
000000000009968f l     F .text  0000000000000162              libcurl_close
00000000002ad100 l     O .data.rel.ro   0000000000000028              libcurl_backend
0000000000099e90 g     F .text  000000000000016e              hfile_plugin_init_libcurl
0000000000099848 g     F .text  0000000000000648              hopen_libcurl
$ cd $CURRENT_DIR
```

The added lines are the following:

```Python
# This is needed for downloading htslib
import urllib

# These are for downloading htslib, and compiling into a static library for later merging into modules
htsfile = urllib.URLopener()
htsfile.retrieve("http://iweb.dl.sourceforge.net/project/samtools/samtools/1.3/htslib-1.3.tar.bz2", "htslib-1.3.tar.bz2")
os.system("tar xjvf htslib-1.3.tar.bz2")
os.system("mv htslib htslib-orig")
os.system("ln -s htslib-1.3 htslib")
savedPath = os.getcwd()
os.chdir("htslib")
os.system("./configure --enable-libcurl")
os.system("make lib-static CFLAGS=-fPIC")
os.chdir(savedPath)

#  These will be needed for chtslib
extra_link_args = []
extra_link_args.append("-Wl,--whole-archive")
extra_link_args.append("htslib/libhts.a")
extra_link_args.append("-Wl,--no-whole-archive")

# This was added to the chtslib module in order to merge all of the htslib/libhts.a static library
    extra_link_args=extra_link_args,
```

If you want the updated `setup.py` file, below is a direct link to download it:

[setup.py](https://www.dropbox.com/s/f9eb7pewyvhbtrr/setup.py?dl=1)

Thus these changes can be performed for any module, and as always comments are appreciated.

Hope it helps and have a great weekend!
Paul

**Comment by jmarshall** [comment]
> htsfile.retrieve("http://iweb.dl.sourceforge.net/project/samtools/samtools/1.3/htslib-1.3.tar.bz2", "htslib-1.3.tar.bz2")

Pysam already bundles a copy of the HTSlib source code.  What's the benefit in downloading another copy?

> $ sed -i "117ios.system(\"./configure --enable-libcurl\")" setup.py
> $ sed -i "118ios.system(\"make lib-static CFLAGS=-fPIC\")" setup.py

Yes, one of these days I mean to add a _libhts_pic.a_ target to HTSlib for the benefit of the Bio::DB::Sam Perl wrapper and similar...

**Comment by pgrosu** [comment]
@jmarshall All roads lead to Rome, and may I assume the second provides a provisional reason for the first :)

**Comment by jeromekelleher** [comment]
Unblocking this, as pysam 0.9.0 support has been merged in #880

**Comment by david4096** [comment]
Here is an example of using pysam with a remote BAM from S3 with a local index file.  This is the internal mechanism the server uses and the behavior seems quite predictable. It takes a little over a second to initially open the file handle, and then up to 2 seconds to respond to randomized fetch requests http://nbviewer.jupyter.org/gist/david4096/545f90664aeb9611d6bc8cb5d5d655ec

**Comment by jeromekelleher** [comment]
Great work @david4096, this is excellent news. Overall the response times look quite good, and I think shouldn't add too much latency to our responses, if we use a reasonably large page size.

**Comment by david4096** [comment]
Although this issue is about AWS, I'm leaving this notebook here that shows behavior across 4 different servers with pysam. It seems azure's byte range functionality is not quite there yet.

http://nbviewer.jupyter.org/gist/david4096/7094a9faf95430e6354332d73b11901c

**Comment by jeromekelleher** [comment]
The link 404s for me @david4096 ...

**Comment by david4096** [comment]
Eh, github does a fine job rendering the ipython notebooks now, updated the link, sorry! @jeromekelleher

**Comment by david4096** [comment]
It appears AWS reads support is acceptable. Remote VCF and FASTA still have a few problems. I would like to close this issue and continued detailed discussion of the VCF issues [here](https://github.com/ga4gh/server/issues/1210) and FASTA [here](https://github.com/ga4gh/server/issues/1162). Objections?

**Comment by jeromekelleher** [comment]
Yes, good call @david4096; closing.
